DROP ALL OBJECTS;
DROP SCHEMA IF EXISTS kc_util;
CREATE SCHEMA kc_util;

CREATE TABLE kc_util.admin (
    ADMIN_ID BIGINT NOT NULL AUTO_INCREMENT,
    LAST_NAME VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255),
    AGE INT,
    PRIMARY KEY (ADMIN_ID)
);

INSERT INTO kc_util.admin (LAST_NAME, FIRST_NAME, AGE) VALUES ('CUBILO', 'KARL MARVIN' , '32');