USE kc_util;

CREATE TABLE admin (
    ADMIN_ID BIGINT NOT NULL AUTO_INCREMENT,
    LAST_NAME VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255),
    AGE INT,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255),
    PRIMARY KEY (ADMIN_ID)
);