# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  pull_request:
    branches: [ "wip" ]
  push:
    branches: [ "wip" ]   
    
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Sonar Cloud
      run:  mvn clean verify sonar:sonar -Dsonar.projectKey=karlcubilo -Dsonar.organization=karlcubilo -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONARCLOUD_TOKEN -Dsonar.scm.disabled=true 
      env:
        GIT_HUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
        SONARCLOUD_TOKEN: ${{ secrets.SONAR_TOKEN }}

  package:
    name: Package Application
    runs-on: ubuntu-latest
    needs: [build]
    if:
      contains('wip', github.ref)
    steps:
      - name: Deployment
        run: echo 'Test Package'

  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [package]
    if:
      contains('wip', github.ref)
    steps:
      - name: Deployment
        run: echo 'Test Deployment'
      
  
